import { NextRequest, NextResponse } from "next/server";

type PdfSection = {
  heading?: string;
  body?: string;
};

type PdfPacket = {
  title?: string;
  forum?: string;
  officialRoute?: string;
  generatedDocument?: {
    title?: string;
    fileName?: string;
    officialRoute?: string;
    sourceUrl?: string;
    sections?: PdfSection[];
  };
};

const pageWidth = 595;
const pageHeight = 842;
const margin = 52;
const lineHeight = 15;
const bodySize = 10;
const headingSize = 13;
const titleSize = 18;

export async function POST(request: NextRequest) {
  const body = (await request.json().catch(() => ({}))) as { packet?: PdfPacket };
  const packet = body.packet;

  if (!packet?.generatedDocument) {
    return NextResponse.json({ error: "Generated document is required." }, { status: 400 });
  }

  const pdf = buildPdf(packet);
  const fileName = sanitizeFileName(packet.generatedDocument.fileName || "caseway-draft.pdf");

  return new NextResponse(pdf, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Cache-Control": "no-store",
    },
  });
}

function buildPdf(packet: PdfPacket) {
  const doc = packet.generatedDocument;
  const lines: Array<{ text: string; size: number; font: "F1" | "F2"; gapAfter?: number }> = [];
  lines.push({ text: doc?.title || packet.title || "Caseway Draft", size: titleSize, font: "F2", gapAfter: 8 });
  lines.push({ text: packet.forum || "", size: bodySize, font: "F1", gapAfter: 10 });

  if (doc?.officialRoute) {
    lines.push({ text: "Official route", size: headingSize, font: "F2", gapAfter: 3 });
    pushWrapped(lines, doc.officialRoute, bodySize, "F1", 90);
  }

  for (const section of doc?.sections || []) {
    if (section.heading) {
      lines.push({ text: section.heading, size: headingSize, font: "F2", gapAfter: 3 });
    }
    if (section.body) {
      pushWrapped(lines, section.body, bodySize, "F1", 88);
    }
  }

  if (doc?.sourceUrl) {
    lines.push({ text: "Official source", size: headingSize, font: "F2", gapAfter: 3 });
    pushWrapped(lines, doc.sourceUrl, bodySize, "F1", 88);
  }

  lines.push({
    text: "Generated by Caseway for review. Verify all facts, signatures, limitation, forum, fees, annexures, and professional review requirements before filing or dispatch.",
    size: bodySize,
    font: "F1",
  });

  const pages = paginate(lines);
  return encodePdf(pages);
}

function pushWrapped(
  lines: Array<{ text: string; size: number; font: "F1" | "F2"; gapAfter?: number }>,
  text: string,
  size: number,
  font: "F1" | "F2",
  maxChars: number,
) {
  const paragraphs = text.split("\n");
  for (const paragraph of paragraphs) {
    const words = paragraph.trim().split(/\s+/).filter(Boolean);
    if (words.length === 0) {
      lines.push({ text: "", size, font, gapAfter: 4 });
      continue;
    }
    let line = "";
    for (const word of words) {
      const next = line ? `${line} ${word}` : word;
      if (next.length > maxChars && line) {
        lines.push({ text: line, size, font });
        line = word;
      } else {
        line = next;
      }
    }
    if (line) lines.push({ text: line, size, font, gapAfter: 8 });
  }
}

function paginate(lines: Array<{ text: string; size: number; font: "F1" | "F2"; gapAfter?: number }>) {
  const pages: typeof lines[] = [[]];
  let cursorY = pageHeight - margin;

  for (const line of lines) {
    const needed = lineHeight + (line.gapAfter || 0);
    if (cursorY - needed < margin) {
      pages.push([]);
      cursorY = pageHeight - margin;
    }
    pages[pages.length - 1].push(line);
    cursorY -= needed;
  }

  return pages;
}

function encodePdf(pages: Array<Array<{ text: string; size: number; font: "F1" | "F2"; gapAfter?: number }>>) {
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
  ];

  const pageRefs: number[] = [];
  const contentRefs: number[] = [];

  for (const page of pages) {
    const content = pageContent(page);
    const contentRef = objects.length + 1;
    objects.push(`<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`);
    const pageRef = objects.length + 1;
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentRef} 0 R >>`);
    contentRefs.push(contentRef);
    pageRefs.push(pageRef);
  }

  objects[1] = `<< /Type /Pages /Kids [${pageRefs.map((ref) => `${ref} 0 R`).join(" ")}] /Count ${pageRefs.length} >>`;

  let output = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(output, "utf8"));
    output += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefStart = Buffer.byteLength(output, "utf8");
  output += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets.slice(1)) {
    output += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  output += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return Buffer.from(output, "utf8");
}

function pageContent(lines: Array<{ text: string; size: number; font: "F1" | "F2"; gapAfter?: number }>) {
  let y = pageHeight - margin;
  let content = "BT\n";
  for (const line of lines) {
    content += `/${line.font} ${line.size} Tf\n1 0 0 1 ${margin} ${y} Tm\n(${escapePdf(line.text)}) Tj\n`;
    y -= lineHeight + (line.gapAfter || 0);
  }
  content += "ET";
  return content;
}

function escapePdf(text: string) {
  return text
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, (char) => {
      if (char === "₹") return "Rs";
      return "";
    })
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function sanitizeFileName(fileName: string) {
  const safe = fileName.replace(/[^a-z0-9._-]/gi, "-").replace(/-+/g, "-");
  return safe.toLowerCase().endsWith(".pdf") ? safe : `${safe}.pdf`;
}
