export const mockUser = {
  name: "Farzeen Ilyas",
  email: "farzeen@caseway.demo",
  phone: "+91 98765 43210",
  city: "Srinagar",
  provider: "Caseway demo",
  avatarSeed: "Caseway User",
  joined: "September 2026",
};

export const savedFilings = [
  {
    id: "filing_itr_2026",
    title: "Income tax filing organizer",
    status: "Draft packet",
    progress: 72,
    forum: "Income Tax e-Filing Portal",
    updatedAt: "Today",
  },
  {
    id: "filing_consumer_refund",
    title: "Consumer complaint for refund",
    status: "Ready for review",
    progress: 94,
    forum: "e-Jagriti / District Consumer Commission",
    updatedAt: "Yesterday",
  },
  {
    id: "filing_dl_renewal",
    title: "Driving licence renewal",
    status: "Portal handoff",
    progress: 58,
    forum: "Parivahan / Sarathi",
    updatedAt: "2 days ago",
  },
];

export const savedDocuments = [
  {
    id: "doc_pan",
    name: "PAN card",
    type: "Identity",
    status: "Self-attested",
    source: "Uploaded",
    retention: "Workflow only",
  },
  {
    id: "doc_invoice",
    name: "Purchase invoice",
    type: "Evidence",
    status: "Extracted",
    source: "Chat upload",
    retention: "Delete after case close",
  },
  {
    id: "doc_notice",
    name: "Legal notice draft",
    type: "Legal document",
    status: "Needs review",
    source: "Generated by Caseway",
    retention: "User profile",
  },
  {
    id: "doc_dl",
    name: "Driving licence",
    type: "Transport",
    status: "Pending DigiLocker",
    source: "DigiLocker-ready",
    retention: "Workflow only",
  },
];

export const accountSettings = [
  {
    label: "Require final confirmation before filings",
    value: "On",
  },
  {
    label: "Store uploaded documents after workflow completion",
    value: "Off",
  },
  {
    label: "Use DigiLocker documents when connected",
    value: "Ask every time",
  },
  {
    label: "Email filing packet summaries",
    value: "On",
  },
];
